version: "3.8"

services:
  otel-collector:
    image: otel/opentelemetry-collector:latest
    container_name: otel-collector
    ports:
      - "4317:4317" # gRPC (OTLP)
      - "4318:4318" # HTTP (OTLP)
    volumes:
      - ./otel-config.yaml:/otel/config.yaml:ro
    command: ["--config", "/otel/config.yaml"]

  oteltui:
    image: ymtdzzz/otel-tui:latest
    container_name: otel-tui
    stdin_open: true
    tty: true
    entrypoint: ["/otel-tui"]
