name: Python SDK

on:
  push:
    tags:
      - "*"
    branches:
      - "main"

jobs:
  pypi-publish:
    name: Upload to PyPI
    runs-on: ubuntu-latest
    environment: release
    permissions:
      # For PyPI's trusted publishing.
      id-token: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-tags: true
          fetch-depth: 0
      - name: "Install uv"
        uses: astral-sh/setup-uv@v4
      - name: Set version
        if: startsWith(github.ref, 'refs/tags')
        run: |
          VERSION="${{ github.ref_name }}"
          VERSION="${VERSION#v}"
          echo "Setting version to $VERSION"
          sed -i -E 's/^version = .*/version = "${VERSION}"/' sdk-python/pyproject.toml
      - name: Set version
        if: startsWith(github.ref, 'refs/tags') != true
        run: |
          echo ${{ github.ref }}
          echo "Setting version to ${{ github.ref_name }}"
          VERSION=$(git describe --tags --abbrev=0)
          VERSION="${VERSION#v}"
          echo "Current version: $VERSION"
          sed -i -E "s/^version = .*/version = \"${VERSION}.pre-${{ github.run_number }}\"/" sdk-python/pyproject.toml
      - name: Publish to PyPi
        run: |
          uv build sdk-python
          uv publish -v --trusted-publishing automatic sdk-python/dist/*
